project:
  type: website

execute:
  freeze: auto

website:
  title: "cjber.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: ~/drive/bib/references.bib
