project:
  type: manuscript

other-links: [{href: https://github.com/cjber/ger-wiki, icon: github, rel: icon, text: Github Repository}, {href:  https://doi.org/10.5454/JPSv1i220161014, icon: journal-richtext, rel: icon, text: DOI 10.1080/13658816.2022.2133125}]
